spring:
  application:
    name: spring-cloud-report
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql8:3306/microService
    username: root
    password: root
server:
  port: 8763
eureka:
  client:
    serviceUrl:
     defaultZone: http://spring-eureka:8761/eureka
    fetch-registry: true
    preferIpAddress: true
  instance:
    lease-renewal-interval-in-seconds: 10